version: '3'

services:
  web:
    build: .
    command: python manage.py collectstatic
    command: gunicorn Alfred.wsgi:application --bind 0.0.0.0:80 --workers=3
    volumes:
      - .:/code
    ports:
      - "80:80"
